only write composer.json if there are changes
silverstripe/recipe-plugin pull request #21
Opened 2022-05-02 05:25 UTC by andrewandante

Caught this on a deployment to one of our platforms, even though no changes were made, the file was still read into memory and rewritten. Unfortunately, that triggered this issue: https://github.com/composer/composer/issues/9515 with an empty `"scripts": {}` key being rewritten to `"scripts": []`

This doesn't totally fix it but it does prevent a few unnecessary writes and saves the day in that one use-case

2022-05-02 21:27 UTC, dhensby commented on src/RecipeInstaller.php
> +            }
I feel that `$anyChanges = $anyChanges || $skipped === false` is a bit clearer that we are trying to keep the `$anyChanges` value or set it to true if `$skipped` is false. It required a double-take for me to see what was going on with this construct

2022-05-02 21:47 UTC, andrewandante commented on src/RecipeInstaller.php
> +            }
Fair, have updated

2022-05-09 01:16 UTC, GuySartorelli commented
Probably worth creating an issue for the underlying problem as well.

2022-05-09 05:19 UTC, emteknetnz requested changes

2022-05-09 05:19 UTC, emteknetnz commented on src/RecipeInstaller.php
> +    protected function installProjectFile($sourceRoot, $destinationRoot, $sourcePath, $installedFiles): array
```suggestion
    protected function installProjectFile($sourceRoot, $destinationRoot, $sourcePath, $installedFiles)
```
This would be an API change.  Protected methods are API.

Changing the actual return to an array is also functionally an API change ... so not something we really want to do

Creating a private field `$skippedModules = []` and updating it within `installProjectFile()` might work as an alternative?

2022-05-09 08:33 UTC, andrewandante commented on src/RecipeInstaller.php
> +    protected function installProjectFile($sourceRoot, $destinationRoot, $sourcePath, $installedFiles): array
Reworked in a non-API-breaking way 🧷

2022-05-09 08:41 UTC, dhensby commented on src/RecipeInstaller.php
> +        if (count($this->writtenFiles) > 0) {
The Boolean check was better or you should use `!empty()`

2022-05-09 09:45 UTC, emteknetnz commented on src/RecipeInstaller.php
> +    protected function installProjectFile($sourceRoot, $destinationRoot, $sourcePath, $installedFiles): array
Great ta. Is there a scenario where this method is going to be called more than once? If so, we'll need to reset the bool back to false after we're done using it

2022-05-09 10:06 UTC, andrewandante commented on src/RecipeInstaller.php
> +    protected function installProjectFile($sourceRoot, $destinationRoot, $sourcePath, $installedFiles): array
Ah yeah I see that if there are `project-files` and `public-files` then it will go twice through the loop. In that case it would write a second time, even if there was nothing else to write. So that's probably enough of a use-case to reset the value.

2022-05-09 21:39 UTC, emteknetnz approved these changes
Looks good

2022-05-09 21:40 UTC, merged

2022-05-09 21:44 UTC, emteknetnz commented
@andrewandante [1.7.0](https://github.com/silverstripe/recipe-plugin/releases/tag/1.7.0)